{
	"template":"Double Base Layer (HTML Edition)",
	"version":"6.7.2beta1_b1,535 (2013-11-19 1107)",
	"boundingBox":"-10496603.693999998 3341414.765 -9881916.566000002 3924918.455",
	"layers":[
	{
		"type":"base-layer",
		"id":"_louisiana_parishes.shp1",
		"name":"louisiana_parishes.shp",
		"geometry":"polygon",
		"url":"_louisiana_parishes.shp1.js",
		"visible":true,
		"symbolSize":15,
		"fillColor":"#ffffff",
		"fillOpacity":0.8,
		"borderColor":"#cccccc",
		"borderThickness":1,
		"showLabels":false,
		"minLabelExtent":0,
		"maxLabelExtent":1000000,
		"iconPath":"",
		"showDataTips":true,
		"showInLayerList":true
	},
	{
		"type":"base-layer",
		"id":"_louisiana_parishes_centroids.shp2",
		"name":"louisiana_parishes_centroids.shp",
		"geometry":"point",
		"url":"_louisiana_parishes_centroids.shp2.js",
		"visible":true,
		"symbolSize":15,
		"fillColor":"#ffffff",
		"fillOpacity":0.8,
		"borderColor":"#cccccc",
		"borderThickness":1,
		"showLabels":false,
		"minLabelExtent":0,
		"maxLabelExtent":1000000,
		"iconPath":"",
		"showDataTips":true,
		"showInLayerList":true
	},
	{
		"type":"ags-layer",
		"id":"wms1631219373",
		"name":"Light Gray Canvas",
		"geometry":"image",
		"visible":true,
		"url":"https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer//export?",
		"tile":true,
		"layers":"0",
		"srs":"102100",
		"params":"",
		"showInLayerList":true
	}
	]
}